### ISSUE TITLE
Add license to specification text

### ISSUE THREAD

**Issue by imphil** [riscv/riscv-trace-spec#40]
The trace specification document doesn't contain any license statement, even though the [repository says it's CC-BY 4.0](https://github.com/riscv/riscv-trace-spec/blob/master/LICENSE). Could you add this information to the specification itself?

**Comment by cetola** [comment]
Hey @imphil, sorry this issue has dragged on a bit. We're currently reviewing how we generate specifications for RISC-V and the copyright / software licenses that we will be using as best practices. For now we are not going to update the repo, but know that this will be addressed long term.
