### ISSUE TITLE
tvalepc for illegal instruction

### ISSUE THREAD

**Issue by weiqi7777** [riscv/riscv-trace-spec#45]
hi:
from table 7.2, the tvalepc description:

> **Exception address if ecause is 2** and interrupt is 0(illegal instruction exception), or trap value otherwise

but for section 7.3.1.

> This field reports the address of illegal instructions, or the trap value otherwise. This ensures
that the address of the faulting instruction is reported for all required cases. The trap value is
set to the address of the faulting instruction for hardware breakpoints, access or page faults and
instructions, loads or stores that are mis-aligned, **but not for illegal instructions (for which it is set
to the opcode)**

the two descriptions are not match for illegal instruction.   
which description is correct?

thanks
lujun

**Comment by IainCRobertson** [comment]
Lujun,
             The descriptions are correct and consistent.  The ‘trap value’ in both sections refers to the tval input provided by the HART.  “This field” in section 7.3.1 is tvalepc.

**Comment by weiqi7777** [comment]
thanks for yout replay
